workflows:
  ios-release-no-shorebird:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Force Update Podfile to iOS 14.0
        script: |
          cd ios
          # 1. Remove any existing platform definition (handled robustly)
          sed -i '' '/platform :ios/d' Podfile
          
          # 2. Create a new Podfile with iOS 14.0 at the top
          echo "platform :ios, '14.0'" > Podfile.tmp
          cat Podfile >> Podfile.tmp
          mv Podfile.tmp Podfile
          
          # 3. Remove lockfile and install dependencies
          rm -f Podfile.lock
          pod install --repo-update
      - name: Build iOS simulator
        script: flutter build ios --simulator --no-codesign
      - name: Package Runner.app
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip
