workflows:
  ios-release-no-shorebird:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and Setup
        script: |
          flutter clean
          flutter pub get
      - name: Force Update Podfile and Install
        script: |
          cd ios
          rm -f Podfile.lock
          pod install --repo-update
          cd ..
      - name: Build iOS simulator
        script: flutter build ios --simulator --no-codesign
      - name: Package Runner.app
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip
