workflows:
  ios-release-no-shorebird:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: CocoaPods repo update and install
        script: |
          cd ios
          pod repo update
          pod update Firebase/Firestore
          pod install
          cd ..
      - name: Build iOS simulator
        script: flutter build ios --simulator --no-codesign
      - name: Package Runner.app
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip
