workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: latest
      groups:
        - Trunri # <-- MUST MATCH your API Key Reference Name in Codemagic
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace" 
        XCODE_SCHEME: "Runner"

    scripts:
      - name: Set up keychain and certificates
        script: |
          keychain initialize
          # Fetch signing files using the API Key from the 'groups' section
          # "IOS_APP_STORE" is required for TestFlight/App Store
          app-store-connect fetch-signing-files "$(xcode-project detect-bundle-id)" --type IOS_APP_STORE --create
          keychain add-certificates

      - name: Set up provisioning profile
        script: |
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          # repo-update ensures we get the latest specs to avoid version errors
          pod install --repo-update
          cd ..

      - name: Build IPA for Distribution
        script: |
          # Build the release IPA using the export options generated by Codemagic
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        # Use the same reference name as in the 'groups' section
        auth: integration 
        
        # Automatically submit to TestFlight beta review
        submit_to_testflight: true 
        
        # (Optional) If you want to expire the build to save build minutes once uploaded
        # submit_to_app_store: false
