workflows:
  ios-release-no-shorebird:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Flutter and iOS artifacts
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData
          
      - name: Fix xcodeproj gem version
        script: |
          sudo gem uninstall xcodeproj --all --ignore-dependencies
          sudo gem install xcodeproj --version=1.25.0
          
      - name: Get Flutter dependencies
        script: flutter pub get
        
      - name: Clean and install CocoaPods
        script: |
          cd ios
          pod cache clean --all
          pod deintegrate || true
          pod install --repo-update
          cd ..
          
      - name: Build iOS simulator
        script: flutter build ios --simulator --no-codesign
        
      - name: Package Runner.app
        script: |
          mkdir -p build/ios/ipa
          zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip
