workflows:
  ios-testflight:
    name: iOS TestFlight Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    
    environment:
      flutter: stable
      xcode: latest
      # Removed 'groups' section as we are using 'integrations' below
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.trunri.www
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"

    # vvv ADD THIS SECTION vvv
    integrations:
      app_store_connect: Trunri # <-- REPLACE THIS with your actual API Key Reference Name
    # ^^^ ADD THIS SECTION ^^^                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

    scripts:
      - name: Set up keychain and certificates
        script: |
          keychain initialize
          keychain add-certificates --certificate

      - name: Set up provisioning profile
        script: |
          xcode-project use-profiles

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA for Distribution
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration # This now correctly refers to the 'integrations' block above
        submit_to_testflight: true
